name: stashcard
description: "Stashcard - A Flutter app for managing your cards"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  mobile_scanner: ^6.0.5
  sqflite: ^2.4.1
  path: ^1.9.0
  syncfusion_flutter_barcodes: ^28.2.3
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/cardCompanies